*******************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.               *
*   NEVER CHANGE IT MANUALLY, PLEASE!                             *
*******************************************************************
FUNCTION $$UNIT$$ Z_APP_LW

    EXPORTING
       REFERENCE(EX_P1) TYPE REF TO !STRING
    RAISING
       !CX_SY_ZERODIVIDE
       RESUMABLE(CX_SY_ASSIGN_CAST_ERROR) .